### ISSUE TITLE
Some Suggestions 

### ISSUE THREAD

**Issue by CoccaGuo** [a858438680/mysterious-crawler#1]
The readme files mentioned that by changing some strings in the main.py file we will get more beautiful things, but it's not easy for these who are not familiar with it or cs issues, and we just do not know where to make the change.
Plus, the default illustrations are not attractive enough, use your server to give an access to the R18G module in pixiv will be a better choice.

**Comment by a858438680** [comment]
pay attention to the base64 encoded string
